server:
  port: 8085
  servlet:
    context-path: /api

spring:
  cloud:
    gateway:
      routes:
      - id: FLIGHT-SERVICE
        uri: http://localhost:8081/
        predicates:
        - Path=/flights/**
      - id: BOOKING-SERVICE
        uri: http://localhost:8084/
        predicates:
        - Path=/booking/**
  application:
        name: gateway-service
  datasource:
        password: pass@word1
        url: jdbc:mysql:/localhost:3306/users?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
  jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        defer-datasource-initialization: true
        
management:
    endpoints:
        web:
            exposure:
                include: '*'
                
logging:
    file:
        name: gateway-service.log
        
jwt:
  secret: jwtzuul