server:
  servlet:
    context-path: /airlines
spring:
    application:
        name: flight-service
    datasource:
        password: pass@1234
        url: jdbc:mysql:/localhost:3306/airlines?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create
        defer-datasource-initialization: true
management:
    endpoints:
        web:
            exposure:
                include: '*'
logging:
    file:
        name: flight-service.log