server:
  port: 8084
  servlet:
    context-path: /bookings
spring:
  application:
    name: booking-service
  datasource:
    password: pass@word1
    url: jdbc:mysql:/localhost:3306/bookings?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
  jpa:
      show-sql: true
      hibernate:
          ddl-auto: update
      defer-datasource-initialization: true
      
management:
    endpoints:
        web:
            exposure:
                include: '*'
logging:
    file:
        name: booking-service.log
