spring:
  cloud:
    gateway:
      routes:
      - id: FLIGHT-SERVICE
        uri: http://localhost:8081/
        predicates:
        - Path=/flights/**
      - id: BOOKING-SERVICE
        uri: http://localhost:8082/
        predicates:
        - Path=/booking/**