server:
  port: 8088
  servlet:
    context-path: /airlines
  
spring:
    application:
        name: flight-service
    datasource:
        password: pass@word1
        url: jdbc:mysql:/localhost:3306/airlines?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        defer-datasource-initialization: true
management:
    endpoints:
        web:
            exposure:
                include: '*'
logging:
    file:
        name: flight-service.log